- user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: install commonly used packages
  yum: name={{ item }} state=present
  with_items:
  - wget
  - emacs
  tags:
  - hdp-base

- name: create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  tags:
  - hdp-base

- name: stop iptables service
  service: name={{ item }} state=stopped
  with_items:
  - iptables
  tags:
  - hdp-base
