#- user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: install commonly used packages
  yum: name={{ item }} state=present
  with_items:
  - wget
  - emacs
  tags:
  - hdp-base

- name: stop iptables service
  service: name={{ item }} state=stopped
  with_items:
  - iptables
  tags:
  - hdp-base
