- name: download ambari repo
  get_url: url=http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.4.3.38/ambari.repo dest=/etc/yum.repos.d/

- name: install ambari prerequisites
  yum: name={{ item }} state=present
  with_items:
  - ntp
  - wget
  - httpd
  - emacs
  - ambari-server
  tags:
  - ambari-base

- name: make services autotstart at boot
  shell: chkconfig {{ item }} on
  with_items:
  - ntpd
  - httpd
  tags:
  - ambari-base

- name: start services
  service: name={{ item }} state=started
  with_items:
  - ntpd
  - httpd
  tags:
  - ambari-base

- name: stop iptables service
  service: name={{ item }} state=stopped
  with_items:
  - iptables
  tags:
  - ambari-base


- name: Setup if ambari-server not running	
  command: "ambari-server setup -s"



#- name: Configure and start ambari server
#  shell: "{{ item }} & touch /tmp/ambariserverinstalled" 
#  with_items:
#  - ambari-server setup -s
#  args:
#    creates: /tmp/ambariserverinstalled
#  tags:
#  - ambari-base

- name: start ambari server and enabled at reboot
  service: name=ambari-server state=started enabled=yes
  tags:
  - ambari-base
